[theme]
base = "dark"

# Premium Deep Sea Blue Mode
textColor = "#E0F7FA"
primaryColor = "#00B4D8"
backgroundColor = "#03045E"
secondaryBackgroundColor = "#0077B6"

# Widgets
showWidgetBorder = true
borderColor = "#334155"

# Base text
font = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
baseFontWeight = 400
baseFontSize = 14

# Heading text
headingFont = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
headingFontWeights = [600, 300, 600]
headingFontSizes = ["3rem", "2rem", "1rem"]
